issues:
  max-same-issues: 0
  exclude-rules: 
  - linters: 
    - revive
    text:  "var-naming"
  - linters: 
    - revive
    text:  "exported"
linters:
  enable:
    - asciicheck
    - durationcheck
    - errorlint
    - gci
    - gofmt
    - gofumpt
    - gosimple
    - misspell
    - nolintlint
    - revive
    - typecheck
    - unparam
  disable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - varcheck
