issues:
  max-same-issues: 0
linters:
  enable:
    - errorlint
    - gci
    - gosimple
    - typecheck
    - unparam
  disable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - varcheck
