linters:
  enable:
    - errorlint
    - gci
    - gosimple
    - typecheck
  disable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - varcheck
